## db test
version: "3.8"

services:
  db:
    image: mysql:8.2.0
    container_name: test-db
    volumes:
      - ./dbvol/data/db:/var/lib/mysql
    environment: 
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASS}"
      - "MYSQL_DATABASE=${DB_NAME}"
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
